# Generated by Django 6.0 on 2026-01-22 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0002_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=150, unique=True)),
                ('User_Email', models.EmailField(max_length=254, unique=True)),
                ('User_Password', models.CharField(max_length=12, unique=True)),
            ],
        ),
    ]
