# Generated by Django 6.0 on 2026-01-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='User_Password',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_Password',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
