# Generated by Django 6.0 on 2026-01-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0004_alter_signup_user_password_alter_user_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='user', max_length=255),
        ),
    ]
