# Generated by Django 6.0 on 2025-12-31 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysecondapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BooK_Name', models.CharField(max_length=150)),
                ('Book_Author', models.CharField(max_length=150)),
                ('Book_Price', models.IntegerField()),
                ('Book_Type', models.CharField(max_length=30)),
            ],
        ),
    ]
