# Generated by Django 6.0 on 2025-12-31 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysecondapp', '0002_bookdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookdetails',
            old_name='BooK_Name',
            new_name='Book_Name',
        ),
    ]
